### ISSUE TITLE
lImitation to 256 Bytes

### ISSUE THREAD

**Issue by samuelruckli** [Hopperpop/node-red-contrib-nvl#5]
https://github.com/Hopperpop/node-red-contrib-nvl/blob/4a09cb321be9ab29caa4010c48c939d0f28ebc86/src/nvl-helper.js#L21

Is it nessecary to limit the NVLs to 256 bytes? Because of technical reasons? If true, are they easy to fix?

I need to communicate with a struct, thats alone bigger than this. It would be cool, if it worked without changing the struct.

**Comment by Hopperpop** [comment]
NVLs larger than 256 are split into separate data messages. First it wasn't fully clear to me how it worked, but I have figured it out. 
It's already implemented here 95c054850ac5f278642f45b2c7e58e8321f277af, but I still need to test it further and wrap it up. The plan was also to add support to import/export nvl definitions, and make a new version. 

I will see if I find some time during the holidays to finish it. I would appreciate it if you could test the development branch and give feedback if it works.

**Comment by Hopperpop** [comment]
New version v1.2.0 released.
