### ISSUE TITLE
Did I miss ?

### ISSUE THREAD

**Issue by Foudtz** [Hopperpop/node-red-contrib-nvl#6]
Hi !

I've just tested your package, can't figure why it does not work :( !
Can you help me ?

On Codesys, created a NVL_Sender: 
![image](https://github.com/Hopperpop/node-red-contrib-nvl/assets/108090081/8fe1f49c-d902-4827-8746-b3c034676c85)

On Node-Red, created a Receiver:
![image](https://github.com/Hopperpop/node-red-contrib-nvl/assets/108090081/5dfc3485-557a-4f5f-8bb5-d295a70e9107)

But there is nothing happening

I am missing something ?
Thanks

**Comment by Foudtz** [comment]
My bad, missed to add the "udp" node :/

**Comment by Hopperpop** [comment]
Correct. The node only parses the protocol. I have played with the idea to build the udp connection into the nodes. 
But some concerns (that I can't remember at the moment 😄 ) held me back.

**Comment by Foudtz** [comment]
I guess it's not necessary to create it, this node already exist and your parser looks great !
Good job !
