### ISSUE TITLE
NVL stops parsing data

### ISSUE THREAD

**Issue by laaccount** [Hopperpop/node-red-contrib-nvl#7]
I have an implementation of Codesys and node red on a CM4 pi module.  Everything works well for some time but after 6-10 hours of 500ms updates the NVL-receive node stops responding to what appears to be valid UDP packets.  No errors are thrown.  I've tried changing the list ID and the node responds with invalid ID so it is working on some level.  Restarting the flow, restarting the service and restarting the Codesys PLC have no impact.  I have to reboot the system for it the flow to start to work properly.  The attached file shows two UPD debug payloads.  The first when the node isn't working.  The second after rebooting the system when the node is working.

[UDP debug.txt](https://github.com/Hopperpop/node-red-contrib-nvl/files/11626564/UDP.debug.txt)

**Comment by Hopperpop** [comment]
It looks like your data is send over at least two udp telegrams. If one of the telegrams isn't send, the node won't output any data.

Can you give me the following:

- Node-red-contrib-nvl version
- Nvl definition
- Multiple sequential udp messages when it's failing
- The Codesys settings for the sending nvl (packed, cyclic/event based,...)

**Comment by laaccount** [comment]
[NVL_PRESS_RESULTS_W.txt](https://github.com/Hopperpop/node-red-contrib-nvl/files/11639196/NVL_PRESS_RESULTS_W.txt)

UPD packet when instruction is failing to respond
{"payload":[0,45,83,51,0,0,0,0,1,0,0,0,13,0,131,0,233,140,0,0,78,169,251,63,242,21,199,65,33,9,237,65,243,39,127,66,160,167,31,66,212,65,11,66,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1],"fromip":"192.168.115.200:42394","ip":"192.168.115.200","port":42394,"_msgid":"3ccbeb688748f17c"}


UDP packet when instruction starts responding after a "reset warm" command is issued to Codesys.  Simply stopping the processor and restarting it via the debug window did not work.

{"payload":[0,45,83,51,0,0,0,0,1,0,0,0,13,0,131,0,104,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"fromip":"192.168.115.200:44993","ip":"192.168.115.200","port":44993,"_msgid":"cf531c48fd6fb43c"}

**Comment by laaccount** [comment]
sorry didn't mean to close the issue...still very much a mystery to me.

**Comment by Hopperpop** [comment]
I think I found the issue. Could you try version 1.2.1, and see if it solves it?

**Comment by laaccount** [comment]
Thank you for the update.  I installed the update today along with
commissioning another instance on another controller.  So I have two
controllers running with error counters.  I'll let you know the results as
I get them.

Steven Martz, CAP

574-524-0436

***@***.***
