### ISSUE TITLE
run on the same device (Codesys and node red)

### ISSUE THREAD

**Issue by H07vk** [Hopperpop/node-red-contrib-nvl#8]
Is it possible to run send and rec on the same device as in the example?
(Codesys and Node-Red)
I can not do it.

**Comment by H07vk** [comment]
for explanation:

I have a Raspi with Codesys and SL license.
My laptop is running Node Red 4. 0.2 with NVL and Contrib-Telegrambot 
it works very well. 
But I want to run both programs on my Raspery.

**Comment by Hopperpop** [comment]
It should be possible. First thing to know is that Codesys and Node-red can't use the same udp port. Choose a differen one in both applications and let each application send the message to the other port.

**Comment by H07vk** [comment]
Thanks.
That was the first solution.
Furthermore, you don't have to set the IP address of the device with UPD-send. You have to set localhost!
Then it works. :-)
Thank you for everything.
